<RootWidget>:

    GridLayout:
        
        cols: 2
        Label:
            text: "Vertex Info: "
        Label:
            text: root.data_model.vertexTextInfo
            
        Label:
            text: "Vertex Outgoing Edges: "
        Label:
            text: root.data_model.vertexOutgoingEdges
            
        Label:
            text: "Vertex Incoming Edges: "
        Label:
            text: root.data_model.vertexIncomingEdges
